name: validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    uses: int128/renovate-config-validator-workflow/.github/workflows/validate.yaml@eb93a44e09135ea370d00b8d4e4d2b9e511e3eed # main
    with:
      config: .github/renovate.* *.json
