name: validate

on:
  pull_request:
    paths:
      - .github/workflows/validate.yaml
      - .github/renovate.*
      - default.json
      - package.json
      - pnpm-lock.yaml
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      - run: npm i -g corepack && corepack enable pnpm
      - run: pnpm i
      - run: pnpm run test
