name: validate

on:
  workflow_call:
    inputs:
      config:
        description: Path(s) to renovate.json
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: int128-renovate-base
          repository: int128/renovate-base
          ref: ${{ github.workflow_sha }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: int128-renovate-base/.node-version
          cache-dependency-path: int128-renovate-base/pnpm-lock.yaml
      - run: corepack enable pnpm
        working-directory: int128-renovate-base
      - run: pnpm i
        working-directory: int128-renovate-base
      - run: pnpm run test ${{ inputs.config }}
        working-directory: int128-renovate-base
