name: validate

on:
  workflow_call:
    inputs:
      config:
        description: Path(s) to renovate.json
        required: false
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: int128-renovate-base
          repository: int128/renovate-base
          ref: ${{ github.job_workflow_sha }}
          # Fetch only the root files
          sparse-checkout: .
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: int128-renovate-base/.node-version
          cache-dependency-path: int128-renovate-base/pnpm-lock.yaml
      - run: corepack enable pnpm
        working-directory: int128-renovate-base
      - run: pnpm i
        working-directory: int128-renovate-base
      - run: |
          "$(cd int128-renovate-base && pnpm root)/.bin/renovate-config-validator" --strict ${{ inputs.config }}
