name: validate

on:
  workflow_call:
    inputs:
      config:
        description: Path(s) to renovate.json
        required: true
        type: string
        default: .github/renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: int128-renovate-base
          repository: int128/renovate-base
          ref: ${{ github.workflow_sha }}
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: int128-renovate-base/.node-version
          cache-dependency-path: int128-renovate-base/pnpm-lock.yaml
      - run: corepack enable pnpm
        working-directory: int128-renovate-base
      - run: pnpm i
        working-directory: int128-renovate-base
      - run: pnpm run test ${{ inputs.config }}
        working-directory: int128-renovate-base
